# Production profile
app:
  allowedOrigins: 'http://localhost:4200'

spring:
  jmx:
    enabled: false
  # Database configurations
  datasource:
    data: classpath*:db/prod/data.sql
    url: jdbc:h2:./db/flightDB
    password: Admin1234
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false

logging.level:
  org:
    hibernate:
      SQL: info
      type.descriptor.sql.BasicBinder: info
    springframework:
      cache: info
      web: debug
    siriusxi:
      htec:
        fa: debug
  web: debug
  root: info
