spring:
  application:
    name: Flight-Management-Service
  mvc:
    servlet:
      path: /fa/api/v1
  # Database configurations
  datasource:
    url: jdbc:h2:./target/data/flightDB
    hikari:
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
    platform: h2
    initialization-mode: embedded
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

# Server configs
server:
  port: 8090
  ## Should be included to show message, if not error message will be empty
  error:
    include-message: always
    include-binding-errors: always

# Application health and information management
management:
  info.git:
    mode: full
    enabled: true
  endpoints.web.exposure.include: "*"
  endpoint:
    shutdown.enabled: true
    health.show-details: always

logging.level:
  org:
    hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    springframework:
      web: DEBUG
    siriusxi:
      htec:
        fa: DEBUG
  web: DEBUG
  root: INFO
