spring:
  application:
    name: Flight-Advisor-Service
  # Database configurations
  datasource:
    data: classpath*:db/data.sql
    schema: classpath*:db/schema.sql
    url: jdbc:h2:./target/data/flightDB
    hikari:
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
    platform: h2
    initialization-mode: embedded
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

# Server configs
server:
  port: 8090
  ## Should be included to show message, if not error message will be empty
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api/v1

# Application health and information management
management:
  info.git:
    mode: full
    enabled: true
  endpoints.web.exposure.include: "*"
  endpoint:
    shutdown.enabled: false
    health.show-details: always

logging.level:
  org:
    hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    springframework:
      web: DEBUG
    siriusxi:
      htec:
        fa: DEBUG
  web: DEBUG
  root: INFO