# Custom application properties
app:
  version: 'v1'

# Spring properties
spring:
  application:
    name: Flight-Advisor-Service

  servlet:
    multipart:
      enabled: false
      max-file-size: 10MB
  # Database configurations
  datasource:
    data: classpath*:db/data.sql
    schema: classpath*:db/schema.sql
    url: jdbc:h2:./target/data/flightDB
    hikari:
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
    platform: h2
    initialization-mode: embedded
  h2:
    console:
      enabled: true
      path: /db-console
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none

# Server configs
server:
  port: 8090
  ## Should be included to show message, if not error message will be empty
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /flight/service/api

# Application health and information management
management:
  info.git:
    mode: full
    enabled: true
  endpoints.web.exposure.include: "*"
  endpoint:
    shutdown.enabled: false
    health.show-details: always

# Logging settings
logging.level:
  org:
    hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace
    springframework:
      web: debug
    siriusxi:
      htec:
        fa: debug
  web: debug
  root: info


# OpenAPI (Swagger) settings
springdoc:
  # swagger-ui custom path
  swagger-ui:
    path: /${app.version}/doc/index.html
  # /api-docs endpoint custom path
  api-docs:
    path: /${app.version}/api-docs
  # to display the actuator endpoints.
  show-actuator: false